### ISSUE TITLE
Climate Regulators no longer produce breathable atmospheres.

### ISSUE THREAD

**Issue by jollyroger1618** [N3X15/spacebuild#14]
I've tried bloxgate's patch branch where the environment entity was changed to sbenvironment though they still exhibit the same behavior for me.

**Comment by bloxgate** [comment]
Damn, I know they work when given a constant value for all their variables. Perhaps we need to put defaults in the code somewhere.

**Comment by jollyroger1618** [comment]
Thanks for the reply.  Just tested and I get no love even with constant values.  I used 1200 for max o2, 600 for gravity and 500 for radius.  I also made sure to give it plenty of energy, water and o2.

**Comment by jollyroger1618** [comment]
Just tried it on your server and it works fine.  I do have the static environment thing turned on though.  Going to turn it off and test some more.

**Comment by jollyroger1618** [comment]
SB_StaticEnvironment 1 is what I've been using so that o2 compressors won't matter on spawn.

**Comment by jollyroger1618** [comment]
Woohoo!  Confirmed, climate regs are fine.  SB_StaticEnvironment 1 was the problem.  Makes sense, I guess the climate regs environment gets treated as static as well.  Thanks much Mr. Blox.

**Comment by bloxgate** [comment]
Alright, still needs the constant value for me even with that off. I'll go ahead and add a check for the static environment.

**Comment by bloxgate** [comment]
Looks like the debug checks I've added make it detect its radius properly. How weird.
